### ISSUE TITLE
build html が失敗する

### ISSUE THREAD

**Issue by shkumagai** [sphinxjp/sphinx-users.jp#106]
# TL;DR

build html で以下のエラーが出てビルドに失敗する

<img width="823" alt="image" src="https://github.com/sphinxjp/sphinx-users.jp/assets/387802/51748bf1-40e2-437e-802b-f44e6fc7946d">

https://github.com/sphinxjp/sphinx-users.jp/actions/runs/4972739742/jobs/8898130585#step:9:262

**Comment by shkumagai** [comment]
直接の原因はおそらくこちら
https://github.com/sphinx-doc/sphinx/blob/master/CHANGES#L82

**Comment by shimizukawa** [comment]
sphinxjp theme 作成当時のlayout.htmlの内容そのままでした。
https://github.com/sphinx-doc/sphinx/blob/v1.4/sphinx/themes/basic/layout.html#LL102C1-L109C1

なので、 `macro css` を削除するだけでよさそう。

**Comment by shimizukawa** [comment]
削除じゃダメだったので https://github.com/sphinx-doc/sphinx/blob/v7.0.1/sphinx/themes/basic/layout.html から `macro css()` を移植します。ついでに `macro script()` も移植。
（このあたり継承できないんだっけ？と思いつつ時間がないので対症療法的になおしちゃう）

**Comment by shimizukawa** [comment]
ぐぬぬ・・ jQuery が無くなった影響で `$` 使ってるコードが死んでる。検索ができない

**Comment by shimizukawa** [comment]
https://github.com/sphinxjp/sphinx-users.jp/pull/107
Sphinx7対応しました。そのうちマージします。
どなたかざっくり確認お願いしますー。

**Comment by shimizukawa** [comment]
ビルドが通るようになったので完了にします。
https://sphinx-users.jp/index.html
