### ISSUE TITLE
Sphinxを使用しているサイト

### ISSUE THREAD

**Issue by ghost** [sphinxjp/sphinx-users.jp#13]
[Sphinxを使用しているサイト](http://sphinx-users.jp/example.html)のページに

> もしも、ここに掲載していないものがありましたら、ここのチケットでご一報ください。

と書いてあったので、報告します。

タイトル: 線形代数学
URL: [https://takeo-books.com/linear-algebra/1/](https://takeo-books.com/linear-algebra/1/)
テーマ: alabasterを追加のcssで少しだけアレンジしたもの

**Comment by tk0miya** [comment]
ここにエントリを追加する PR を送っていただけますか。
https://github.com/sphinxjp/sphinx-users.jp/blob/master/source/example.rst

**Comment by cocoatomo** [comment]
既に記載されている。
ただし、リンク切れのため削除の PR #20 を提出。

**Comment by shimizukawa** [comment]
削除マージしました。
