### ISSUE TITLE
Sphinxを使用して執筆された書籍

### ISSUE THREAD

**Issue by orj-takizawa** [sphinxjp/sphinx-users.jp#17]
以下の書籍についてSphinxを使用して翻訳、制作されましたのでご報告申し上げます。サイトへ追加していただけたら幸いです。

- 『仕事ではじめる機械学習』 https://www.oreilly.co.jp/books/9784873118253/
- 『Go言語による並行処理』 https://www.oreilly.co.jp/books/9784873118468/

**Comment by shimizukawa** [comment]
記載しました。ありがとうございます！
