### ISSUE TITLE
Sphinxを使用しているサイトの追加

### ISSUE THREAD

**Issue by cocoatomo** [sphinxjp/sphinx-users.jp#3]
- LLVM: https://llvm.org/docs/
- Asakusa Framework: http://docs.asakusafw.com/latest/release/ja/html/index.html

がまだ掲載されていませんでした. 追加をお願いします.

Asakusa Framework はデフォルト+カスタムに分類されます.

**Comment by shimizukawa** [comment]
Thanks! PR待ってます！

**Comment by shimizukawa** [comment]
マージしたので終了
