### ISSUE TITLE
🎨 ヘッダー部分の削除

### ISSUE THREAD

**Issue by tkoyama010** [sphinxjp/sphinx-users.jp#47]
Sphinx ユーザー会の黒いバーを削除したいと思います🎨
![image](https://user-images.githubusercontent.com/7513610/71320288-8aeea980-24ec-11ea-8677-b41199eb9123.png)
https://sphinx-users.jp/

**Comment by usaturn** [comment]
一番右側のインデックスはどっかに逃がす必要あります

**Comment by tk0miya** [comment]
+1; 索引だけどこかに逃して (とりあえず ToC のところ?)、ばっさりやっちゃいましょう!

**Comment by tkoyama010** [comment]
ToCに入れる方法がわからないので早わかりの下に置いています。

**Comment by tkoyama010** [comment]
theme自体を変えるという道もありますね。

**Comment by tk0miya** [comment]
テーマをリリースしないといけないかと思っていたんですが #48 で直接 github を見るようにしたんですね。この対応でよさそうですね。解消したのでクローズで良いと思います!
