### ISSUE TITLE
♻️ RTDへの移行

### ISSUE THREAD

**Issue by tkoyama010** [sphinxjp/sphinx-users.jp#67]
AWSよりもRTDで運用した方がメンテナンスの負担が少ないと思いますがいかがでしょう。AWSを使うことによる利点がありましたらコメントをお願いいたします。

**Comment by shimizukawa** [comment]
1. RTDではネイキッドドメインを使えない ため、以下の様にURLを変える必要があります。

   http://sphinx-users.jp/ -> http://www.sphinx-users.jp/

2. RTDを使うと時々広告がでます。課金すると広告がでなくなります。S3に使う分の費用をRTDに課金するのが良いかなと思います。

3. https://sphinx-users.jp/doc11/index.html に古いバージョン(sphinx-1.1)のドキュメントがあります。このような配置はRTDではできないですが、さすがにもう削除してよさそう。

4. https://docutils.sphinx-users.jp/ もS3に置いているため、これも移行するかどうか検討するとよさそうです

5. https://docs.sphinx-users.jp/ も存在してますが、これはsphinx-1.4の日本語ドキュメントで、 sphinx-doc.org をRTDに移行する前の遺物なので、さすがにもう削除してよさそう。

**Comment by tkoyama010** [comment]
コメントありがとうございます。本件は #58 とは独立して考えていきたいと思います。

**Comment by tkoyama010** [comment]
> 4. https://docutils.sphinx-users.jp/ もS3に置いているため、これも移行するかどうか検討するとよさそうです

[Docutils](https://github.com/sphinxjp/docutils-translation)のリポジトリはこれですね。[sphinx-doc-translation](https://github.com/sphinx-doc/sphinx-doc-translations)と同じ運用ができる気がします。

**Comment by usaturn** [comment]
@tkoyama010
大分出遅れましたが、AWSを使っている場合のメンテナンスコスト(だと思っている事)と、そのメンテナンスコストを軽減できる RTD の仕組みをあげてもらえますか？

**Comment by tkoyama010** [comment]
@usaturn 
コメントありがとうございます。コストであると思っているのはS3に使う分の費用(だと思っています)。広告が出ることを許容すればその分の費用を削減できると考えています。

**Comment by usaturn** [comment]
@tkoyama010 メンテナンスコストではなく、費用的な意味合いでランニングコストという事ですね（メンテナンスコストはランニングコストに含まれるとは思いますが）。
であれば、金額的にも困っているわけではないし、ドメイン変更と広告が出るというデメリットをおして、RTD に移行する意味はメリットは薄いのではないでしょうか。

また、ドメイン変更については以前 @tk0miya に反対されています。

ですが、ボクは何かあった場合に、現在のデプロイの仕組そのものが、メンテナンスコストが高いと考えています。
理由としては、不具合があったり、何か変更をかけたいと思った場合、調査をする範囲が多岐に渡っていることです。

- github actions
- s3(AWS)
- Cloudfront(AWS)
- ACM(AWS)
- Route53(AWS)

などなど、メモも残していない為、初見の人が調べる場合、AWS に馴染みがないと苦労する事が予想されます。
上記を解決したいのであれば、シンプルな仕組で RTD の広告、ネイキッドドメインの問題を解決するサービスとして以下の3つをあげます。

- Amplify(AWS)
- Netlify
- Vercel

これらのサービスであればリポジトリを指定し、DNS の設定をするだけで公開できますので、変更をかけたり、不具合調査したりする時も楽だと思います。
Netlify、Vercel は無料で使えますが、個人的には Route53 にゾーンがありますし、価格も大した事ないので Amplify がいいかなと思います。

という事で、もしメンテナンスコストを解決したい要望を誰かが出すのであれば、上記3サービスを候補にあげておきます。

**Comment by tk0miya** [comment]
解決したい問題を見極めるのが最初だと思います。
コメントしてもらったように、ランニングコストについては大した金額ではないので (年間 2000円以下)、積極的に変えるほどではないと考えます。

>ですが、ボクは何かあった場合に、現在のデプロイの仕組そのものが、メンテナンスコストが高いと考えています。
理由としては、不具合があったり、何か変更をかけたいと思った場合、調査をする範囲が多岐に渡っていることです。

強い意見はないのですが、本当にメンテナンスコストが高いのでしょうか?
個人的にはどれを選んでも五十歩百歩だと感じます。
使っている技術、ツールへの慣れというだけではないでしょうか。強いてあげるとするとマネージドサービスにすると証明書管理、CDN 部分が減るぐらいで、あとは UI の違いではありませんか (CI, 配信設定, DNS と言った要素はなくならないですよね)。

さらに、「なにか変更をかけたいと思った場合」というコメントの通り、変更をかけると言うこと自体が稀ではないかと考えるので、こちらも同じく積極的に変える理由にはならないと考えます。

**Comment by usaturn** [comment]
@tk0miya
>本当にメンテナンスコストが高いのでしょうか?

現在の方法について言えば、AWS に慣れてない方が一から調べるのと、RTD、Netlify, Vercel Amplify と比べた場合、10倍くらい違うと思います(適当)。
ただし、それが解決すべき問題かどうかについては別です。

ボクは現状でそこまで問題だとは思ってない、かつ積極的に変えたいとも思っていないので
`もしメンテナンスコストを解決したい要望を誰かが出すのであれば`
という表現をしています。

**Comment by tk0miya** [comment]
はい。usaturn がコメントするまで、だれもメンテナンスコストについて触れていなかったので、火のないところに煙を立てているように感じただけです。
今の所だれも問題だと思っていないように思われるのでこの議論はここまでにしましょう。
(もしくは、問題だと思っているのであれば何が問題なのかを整理してからにしましょう。)

**Comment by usaturn** [comment]
@tk0miya 

>AWSよりもRTDで運用した方がメンテナンスの負担が少ないと思いますがいかがでしょう

ISSUE の始まりがこの文だったので、メンテナンスの負担＝メンテナンスコストだと思って、どこがメンテナンスコストと思ってるのかなと投稿した感じですね。

言われてみれば、負担＝支払う料金ともとれるので、はい。
自分のあげたメンテナンスコストについては、その通りなので、気が向いたらissueにあげたいと思います。

RTDへの移行については、このまま意見を待ち続けるかどうか、 @tkoyama010 にお任せします。

**Comment by usaturn** [comment]
はい、すみません。
ランニングコストの話で止めておいて、別で issue 建てるべきでしたね。

**Comment by tkoyama010** [comment]
コメントありがとうございました。このイシューはここで閉じます。
