### ISSUE TITLE
Sphinxを使用して執筆された書籍の追加依頼

### ISSUE THREAD

**Issue by takanory** [sphinxjp/sphinx-users.jp#8]
## 目的

* Sphinxで書いた書籍があるので追加してほしい
* http://sphinx-users.jp/book_usage.html

## 内容

* [Pythonエンジニア養成読本](http://gihyo.jp/book/2015/978-4-7741-7320-7)
* [Python ライブラリ厳選レシピ](http://gihyo.jp/book/2015/978-4-7741-7707-6)
* [Pythonエンジニア ファーストブック](http://gihyo.jp/book/2017/978-4-7741-9222-2)

**Comment by shimizukawa** [comment]
はい、のちほど。
PRもらえると早いです。（or だれか作ってくれないかなー）

**Comment by takanory** [comment]
はい https://github.com/sphinxjp/sphinx-users.jp/pull/9

**Comment by shimizukawa** [comment]
あざーっす！
